import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  public techCarouselItems: string[] = [
    'Java 8-21',
    'Spring Boot',
    'Spring Web',
    'Spring Security',
    'Spring Data',
    'Spring Data JPA',
    'Spring Cloud',
    'Microservices',
    'Angular 17',
    'Angular Material',
    'Angular CDK',
    'Bootstrap 5',
    'TypeScript',
    'JavaScript',
    'SCSS',
    'Docker',
    'Nginx',
    'Kubernetes',
    'Jenkins',
    'Azure DevOps',
    'Maven',
    'Kafka',
    'RabbitMQ',
    'Oracle',
    'PostgreSQL',
    'H2',
    'MongoDB',
    'SonarQube',
    'Grafana',
    'Prometheus',
    'Quarkus',
    'Keycloak',
    'JWT',
    'Auth0 Angular JWT',
    'JUnit',
    'WireMock',
    'RestAssured',
    'RestTemplate',
    'MapStruct',
    'Lombok',
    'Bean Validation',
    'Actuator',
    'OpenAPI',
    'Swagger UI',
    'JasperReports',
    'DTO Pattern',
    'API Versioning',
    'Scrum',
    'Kanban',
    'Arquitetura de Software',
    'HTML5',
    'CSS3',
    'Ajax',
    'Java 7',
    'JSF2',
    'PrimeFaces',
    'Facelets',
    'Hibernate JPA',
    'Hibernate Validator',
    'JavaMail',
    'iReport',
    'Design Patterns',
    'Clean Code',
    'Maven POM'
  ];
}
